from colorist import Color
import numpy as np
import time
from Helper import *


print("------------------------------ Идеал ------------------------------")
print(f"Математическое ожидание: {Color.CYAN}{0.5}{Color.OFF}")
print(f"Дисперсия: {Color.CYAN}{1/12}{Color.OFF}")
print(f"Среднеквадратическое отклонение: {Color.CYAN}{(1/12)**0.5}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0.2113; 0.7887): {Color.CYAN}{(1/12)**0.5 * 2}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0; 0.5): {Color.CYAN}{0.5}{Color.OFF}")
print("-------------------------------------------------------------------\n")

print("-------------------- Для малого значения выборки (20) --------------------")
start_time = time.time()
lst = np.random.beta(1, 1, 20)
end_time = time.time()
m, d, s = get_mds(lst)
f = get_freq_chance(lst)
h = get_half_chance(lst)
print(f"Математическое ожидание: {Color.RED}{m}{Color.OFF}")
print(f"Дисперсия: {Color.RED}{d}{Color.OFF}")
print(f"Среднеквадратическое отклонение: {Color.RED}{s}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0.2113; 0.7887): {Color.RED}{f}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0; 0.5): {Color.RED}{h}{Color.OFF}")
print(f"Время генерации чисел: {Color.RED}{end_time - start_time}{Color.OFF}")
print("--------------------------------------------------------------------------\n")

print("-------------------- Для среднего значения выборки (150) --------------------")
start_time = time.time()
lst = np.random.beta(1, 1, 150)
end_time = time.time()
m, d, s = get_mds(lst)
f = get_freq_chance(lst)
h = get_half_chance(lst)
print(f"Математическое ожидание: {Color.YELLOW}{m}{Color.OFF}")
print(f"Дисперсия: {Color.YELLOW}{d}{Color.OFF}")
print(f"Среднеквадратическое отклонение: {Color.YELLOW}{s}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0.2113; 0.7887): {Color.YELLOW}{f}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0; 0.5): {Color.YELLOW}{h}{Color.OFF}")
print(f"Время генерации чисел: {Color.YELLOW}{end_time - start_time}{Color.OFF}")
print("-----------------------------------------------------------------------------\n")

print("-------------------- Для большого значения выборки (1000000) --------------------")
start_time = time.time()
lst = np.random.beta(1, 1, 1000000)
end_time = time.time()
m, d, s = get_mds(lst)
f = get_freq_chance(lst)
h = get_half_chance(lst)
print(f"Математическое ожидание: {Color.GREEN}{m}{Color.OFF}")
print(f"Дисперсия: {Color.GREEN}{d}{Color.OFF}")
print(f"Среднеквадратическое отклонение: {Color.GREEN}{s}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0.2113; 0.7887): {Color.GREEN}{f}{Color.OFF}")
print(f"Вероятность попадания в диапазон (0; 0.5): {Color.GREEN}{h}{Color.OFF}")
print(f"Время генерации чисел: {Color.GREEN}{end_time - start_time}{Color.OFF}")
print("--------------------------------------------------------------------------------\n")
